# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-24 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180124_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='courses',
            new_name='course_nums',
        ),
    ]
